#Name of your workflow
name: My Test Workflow

#Define the trigger event(s)
on: [push]

#Jobs run in paraller by default,each runs steps in sequence
#Jobs:
#    say-hello:
#        runs-on: ubuntu-latest
#        steps:
#            - run: echo "Hello, Github Actions!"

jobs:
    say_hello:
        runs-on: ubuntu-latest
        steps:
          - run: echo "Hello, Github Actions!"