#Name of your workflow
name: My Test Workflow

#Define the trigger event(s)
on: [push]

#Jobs run in paraller by default,each runs steps in sequence
#Jobs:
#    say-hello:
#        runs-on: ubuntu-latest
#        steps:
#            - run: echo "Hello, Github Actions!"

jobs:
    say_hello:
        runs-on: ubuntu-latest
        steps:
          - run: echo "Hello, Github Actions!"
    
    #Job to build and test c code
    build_and_test:   
        needs: [say_hello]
        runs-on: ubuntu-latest
        steps:
            
            #Use github.com/actions/checkout tocheck this repo
          - name: Check out this repo
            uses: actions/checkout@v3
            
            #install necessary packages
          - name: Install dependencies
            run: sudo apt install -y build-essential python3
            
            #see where we are in the VM
          - run: pwd
      
            #Run our test
          - name: Run test
            run: python3 test.py